<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>fileTypes</key>
    <array>
        <string>conf</string>
    </array>
    <key>name</key>
    <string>LamaConf</string>
    <key>patterns</key>
    <array>
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>string.conf</string>
                </dict>
            </dict>
            <key>match</key>
            <string>\$\[(\w+)\]</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(?&lt;=[\s:])-\w+</string>
            <key>name</key>
            <string>variable.parameter.conf</string>
        </dict>
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>variable.others.conf</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>variable.parameter.conf</string>
                </dict>
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>string.conf</string>
                </dict>
            </dict>
            <key>match</key>
            <string>\$\[\s*([\w=\-]+):?(-\w+\s*)?((?:\#\w+)*)\s*\]</string>
            <key>name</key>
            <string>variables.complete.conf</string>
        </dict>
        <dict>
            <key>match</key>
            <string>^\s*#.*?\n</string>
            <key>name</key>
            <string>comment.conf</string>
        </dict>
        <dict>
            <key>match</key>
            <string>^\s*Name\s*:\s*(.+)\s*$</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>constant.character.escape markup.bold</string>
                </dict>
            </dict>
            <key>name</key>
            <string>keyword</string>
        </dict>
        <dict>
            <key>match</key>
            <string>^\s*Description\s*:(\s*.+\s*)(#.+)?$?</string>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>string.conf</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>comment.conf</string>
                </dict>
            </dict>
            <key>name</key>
            <string>keyword</string>
        </dict>
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>keyword.conf</string>
                </dict>
            </dict>
            <key>match</key>
            <string>^(\s*\w+\s*:)\s*</string>
        </dict>
        <dict>
            <key>match</key>
            <string>#.+$</string>
            <key>name</key>
            <string>comment.in.line.conf</string>
        </dict>
    </array>
    <key>scopeName</key>
    <string>source.lama.conf</string>
    <key>uuid</key>
    <string>54267807-d0bc-4f66-b353-e844c069393a</string>
</dict>
</plist>
